backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "index"
    label: "Page d'accueil"
    files:
      - file: "index.html"
        label: "Modifier la page d'accueil"
        name: "index"   # <-- Ajoutez un nom ici pour identifier ce fichier.
        fields:
          - label: "Titre principal"
            name: "hero_title"
            widget: "string"
          - label: "Texte d'introduction"
            name: "hero_intro"
            widget: "text"
          - label: "Image principale accueil"
            name: "hero_image"
            widget: "image"
