backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "index"
    label: "Page d'accueil"
    files:
      - file: "index.html"
        label: "Modifier la page d'accueil"
        fields:
          - label: "Titre principal"
            name: "hero_title"
            widget: "string"
          - label: "Texte d'introduction"
            name: "hero_intro"
            widget: "text"
          - label: "Image principale accueil"
            name: "hero_image"
            widget: "image"

roles:
  - name: "Editor"
    permissions:
      - edit_content
      - create_content
  - name: "Admin"
    permissions:
      - manage_users
      - edit_content
      - create_content
