backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "index"
    label: "Page d'accueil"
    files:
      - file: "index.html"
        label: "Modifier la page d'accueil"
        fields:
          - label: "Titre principal"
            name: "hero_title"
            widget: "string"
          - label: "Texte d'introduction"
            name: "hero_intro"
            widget: "text"
          - label: "Image principale accueil"
            name: "hero_image"
            widget: "image"

          - label: "Prix Vitrine Bar"
            name: "prix_bar"
            widget: "string"
          - label: "Prix Vitrine Coiffure"
            name: "prix_coiffure"
            widget: "string"
          - label: "Prix Vitrine Auto École"
            name: "prix_auto_ecole"
            widget: "string"

          - label: "Formule Essentielle - Prix"
            name: "formule_essentielle_prix"
            widget: "string"
          - label: "Formule Professionnelle - Prix"
            name: "formule_professionnelle_prix"
            widget: "string"
