backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Page d'accueil"
        fields:
          - label: "Titre principal"
            name: "hero_title"
            widget: "string"
